baseURL = 'https://asurasuu.github.io'
languageCode = 'ru-ru'
theme = 'nightfall'
title = './Asurasuu/.'

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
user = "./Asruasuu/."
published = false
readingTime = false
#hostname = "asurasuu.ru"

  [params.author]
    name = "Andrey Novoselov"
    email = "andrey.novoselov.v@yandex.ru"
    
  [params.meta]
    favicon = true

  [[params.social]]
    key = 0
    name = "github"
    url = "https://github.com/Asurasuu"
    icon = "fa-brands fa-github"
  [[params.social]]
    key = 1
    name = "telegram"
    url = "https://t.me/asurasuutargz"
    icon = "fa-brands fa-telegram"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"
